
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Member_logScalarFieldEnum = {
  id: 'id',
  ip_address: 'ip_address',
  created_at: 'created_at',
  member_id: 'member_id',
  section: 'section',
  sub_section: 'sub_section',
  action: 'action',
  altered: 'altered',
  data: 'data',
  original_data: 'original_data',
  account_id: 'account_id'
};

exports.Prisma.MembersScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  username: 'username',
  first_name: 'first_name',
  last_name: 'last_name',
  google_id: 'google_id',
  email: 'email',
  salt: 'salt',
  algo: 'algo',
  password: 'password',
  email_verification_key: 'email_verification_key',
  verify: 'verify',
  google_key: 'google_key',
  acl_access_profile: 'acl_access_profile',
  user_level: 'user_level',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Member_acl_pathsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  section_name: 'section_name',
  name: 'name',
  route_name: 'route_name',
  path: 'path',
  permission_type: 'permission_type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Member_acl_rulesScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  parent_id: 'parent_id',
  app: 'app',
  minimum_tier_level: 'minimum_tier_level',
  name: 'name',
  section_name: 'section_name',
  require_acl: 'require_acl',
  tutorial_url: 'tutorial_url',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.ServersScalarFieldEnum = {
  id: 'id',
  hostname: 'hostname',
  provision: 'provision',
  close: 'close',
  state: 'state',
  type: 'type',
  last_update_time: 'last_update_time',
  cluster: 'cluster',
  master: 'master',
  master_active: 'master_active',
  projectx_node_version: 'projectx_node_version',
  rvm: 'rvm',
  service: 'service',
  provision_request_value: 'provision_request_value',
  location: 'location',
  instance_id: 'instance_id',
  last_requested_at: 'last_requested_at'
};

exports.Prisma.Servers_ipsScalarFieldEnum = {
  id: 'id',
  servers_id: 'servers_id',
  ip: 'ip',
  comment: 'comment',
  instance: 'instance'
};

exports.Prisma.Servers_propertiesScalarFieldEnum = {
  id: 'id',
  servers_id: 'servers_id',
  name: 'name',
  value: 'value'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.member_logOrderByRelevanceFieldEnum = {
  ip_address: 'ip_address',
  section: 'section',
  sub_section: 'sub_section',
  altered: 'altered',
  data: 'data',
  original_data: 'original_data'
};

exports.Prisma.membersOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  username: 'username',
  first_name: 'first_name',
  last_name: 'last_name',
  google_id: 'google_id',
  email: 'email',
  salt: 'salt',
  algo: 'algo',
  password: 'password',
  email_verification_key: 'email_verification_key',
  google_key: 'google_key'
};

exports.Prisma.member_acl_pathsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  section_name: 'section_name',
  name: 'name',
  route_name: 'route_name',
  path: 'path'
};

exports.Prisma.member_acl_rulesOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  app: 'app',
  name: 'name',
  section_name: 'section_name',
  tutorial_url: 'tutorial_url'
};

exports.Prisma.serversOrderByRelevanceFieldEnum = {
  hostname: 'hostname',
  cluster: 'cluster',
  projectx_node_version: 'projectx_node_version',
  service: 'service',
  location: 'location'
};

exports.Prisma.servers_ipsOrderByRelevanceFieldEnum = {
  ip: 'ip',
  comment: 'comment'
};

exports.Prisma.servers_propertiesOrderByRelevanceFieldEnum = {
  name: 'name',
  value: 'value'
};
exports.member_log_action = exports.$Enums.member_log_action = {
  SAVE: 'SAVE',
  DELETE: 'DELETE'
};

exports.members_verify = exports.$Enums.members_verify = {
  NO: 'NO',
  YES: 'YES'
};

exports.member_acl_paths_permission_type = exports.$Enums.member_acl_paths_permission_type = {
  R: 'R',
  W: 'W',
  D: 'D'
};

exports.member_acl_rules_require_acl = exports.$Enums.member_acl_rules_require_acl = {
  YES: 'YES',
  NO: 'NO'
};

exports.servers_type = exports.$Enums.servers_type = {
  REGULAR: 'REGULAR',
  VB: 'VB'
};

exports.servers_rvm = exports.$Enums.servers_rvm = {
  ZERO: 'ZERO',
  ONE: 'ONE'
};

exports.Prisma.ModelName = {
  member_log: 'member_log',
  members: 'members',
  member_acl_paths: 'member_acl_paths',
  member_acl_rules: 'member_acl_rules',
  servers: 'servers',
  servers_ips: 'servers_ips',
  servers_properties: 'servers_properties'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
