
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UsersScalarFieldEnum = {
  user_id: 'user_id',
  u_id: 'u_id',
  account_id: 'account_id',
  acl_access_profile: 'acl_access_profile',
  agent_acl_profile: 'agent_acl_profile',
  email: 'email',
  first_name: 'first_name',
  last_name: 'last_name',
  user_level: 'user_level',
  phone_login: 'phone_login',
  phone_pass: 'phone_pass',
  hotkeys_active: 'hotkeys_active',
  agent_choose_ingroups: 'agent_choose_ingroups',
  closer_campaigns: 'closer_campaigns',
  scheduled_callbacks: 'scheduled_callbacks',
  agentonly_callbacks: 'agentonly_callbacks',
  callback_email_template: 'callback_email_template',
  cost_per_hour: 'cost_per_hour',
  agentcall_manual: 'agentcall_manual',
  recording: 'recording',
  transfers: 'transfers',
  closer_default_blended: 'closer_default_blended',
  recording_override: 'recording_override',
  alter_custdata_override: 'alter_custdata_override',
  qc_enabled: 'qc_enabled',
  qc_user_level: 'qc_user_level',
  qc_pass: 'qc_pass',
  qc_finish: 'qc_finish',
  qc_commit: 'qc_commit',
  alter_custphone_override: 'alter_custphone_override',
  active: 'active',
  alert_enabled: 'alert_enabled',
  agent_shift_enforcement_override: 'agent_shift_enforcement_override',
  manager_shift_enforcement_override: 'manager_shift_enforcement_override',
  shift_override_flag: 'shift_override_flag',
  local_gmt: 'local_gmt',
  default_callback_gmt_selection: 'default_callback_gmt_selection',
  release_callbacks_in: 'release_callbacks_in',
  choose_blended: 'choose_blended',
  allowed_campaigns: 'allowed_campaigns',
  chat: 'chat',
  realtime_access: 'realtime_access',
  realtime_listen: 'realtime_listen',
  chat_history: 'chat_history',
  auto_mode: 'auto_mode',
  lead_access: 'lead_access',
  notification: 'notification',
  connection_type: 'connection_type',
  connect_using: 'connect_using',
  rtp_timeout: 'rtp_timeout',
  did_id: 'did_id',
  allow_choose_cid: 'allow_choose_cid',
  queue_override: 'queue_override',
  allow_mobile: 'allow_mobile',
  alter_override: 'alter_override',
  last_logged_in: 'last_logged_in',
  auto_id: 'auto_id',
  allow_calling_dnc: 'allow_calling_dnc',
  user_widgets: 'user_widgets',
  allow_agent_to_choose_list: 'allow_agent_to_choose_list',
  default_list_access_level: 'default_list_access_level',
  default_list_for_new_leads: 'default_list_for_new_leads',
  remote_agent: 'remote_agent',
  remote_agent_server_ip: 'remote_agent_server_ip',
  remote_agent_campaign_id: 'remote_agent_campaign_id',
  remote_agent_number: 'remote_agent_number',
  avatar: 'avatar',
  soundboard: 'soundboard',
  custom_fields: 'custom_fields',
  max_inbound_sms: 'max_inbound_sms',
  sms_force_callback_campaign: 'sms_force_callback_campaign',
  terms: 'terms',
  last_agreed_to_terms_at: 'last_agreed_to_terms_at',
  audio_settings: 'audio_settings',
  force_logout: 'force_logout',
  inbound_max_call_count: 'inbound_max_call_count',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  last_missed_calls_seen_at: 'last_missed_calls_seen_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.usersOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  email: 'email',
  first_name: 'first_name',
  last_name: 'last_name',
  phone_login: 'phone_login',
  phone_pass: 'phone_pass',
  closer_campaigns: 'closer_campaigns',
  callback_email_template: 'callback_email_template',
  local_gmt: 'local_gmt',
  choose_blended: 'choose_blended',
  allowed_campaigns: 'allowed_campaigns',
  chat: 'chat',
  realtime_access: 'realtime_access',
  lead_access: 'lead_access',
  did_id: 'did_id',
  user_widgets: 'user_widgets',
  remote_agent_server_ip: 'remote_agent_server_ip',
  remote_agent_number: 'remote_agent_number',
  avatar: 'avatar',
  soundboard: 'soundboard',
  custom_fields: 'custom_fields',
  terms: 'terms',
  audio_settings: 'audio_settings'
};
exports.users_hotkeys_active = exports.$Enums.users_hotkeys_active = {
  HOTKEYS_INACTIVE: 'HOTKEYS_INACTIVE',
  HOTKEYS_ACTIVE: 'HOTKEYS_ACTIVE'
};

exports.users_agent_choose_ingroups = exports.$Enums.users_agent_choose_ingroups = {
  CHOOSE_NO: 'CHOOSE_NO',
  CHOOSE_YES: 'CHOOSE_YES'
};

exports.users_scheduled_callbacks = exports.$Enums.users_scheduled_callbacks = {
  CALLBACKS_DISABLED: 'CALLBACKS_DISABLED',
  CALLBACKS_ENABLED: 'CALLBACKS_ENABLED'
};

exports.users_agentonly_callbacks = exports.$Enums.users_agentonly_callbacks = {
  AGENTONLY_NO: 'AGENTONLY_NO',
  AGENTONLY_YES: 'AGENTONLY_YES',
  AGENTONLY_SOME: 'AGENTONLY_SOME'
};

exports.users_agentcall_manual = exports.$Enums.users_agentcall_manual = {
  MANUAL_NO: 'MANUAL_NO',
  MANUAL_YES: 'MANUAL_YES'
};

exports.users_recording = exports.$Enums.users_recording = {
  RECORDING_OFF: 'RECORDING_OFF',
  RECORDING_ON: 'RECORDING_ON'
};

exports.users_transfers = exports.$Enums.users_transfers = {
  TRANSFERS_OFF: 'TRANSFERS_OFF',
  TRANSFERS_ON: 'TRANSFERS_ON'
};

exports.users_closer_default_blended = exports.$Enums.users_closer_default_blended = {
  CLOSER_DEFAULT_OFF: 'CLOSER_DEFAULT_OFF',
  CLOSER_DEFAULT_ON: 'CLOSER_DEFAULT_ON'
};

exports.users_recording_override = exports.$Enums.users_recording_override = {
  DISABLED: 'DISABLED',
  NEVER: 'NEVER',
  ONDEMAND: 'ONDEMAND',
  ALLCALLS: 'ALLCALLS',
  ALLFORCE: 'ALLFORCE'
};

exports.users_alter_custdata_override = exports.$Enums.users_alter_custdata_override = {
  Y: 'Y',
  N: 'N'
};

exports.users_qc_enabled = exports.$Enums.users_qc_enabled = {
  QC_DISABLED: 'QC_DISABLED',
  QC_ENABLED: 'QC_ENABLED'
};

exports.users_qc_pass = exports.$Enums.users_qc_pass = {
  QC_PASS_NO: 'QC_PASS_NO',
  QC_PASS_YES: 'QC_PASS_YES'
};

exports.users_qc_finish = exports.$Enums.users_qc_finish = {
  QC_FINISH_NO: 'QC_FINISH_NO',
  QC_FINISH_YES: 'QC_FINISH_YES'
};

exports.users_qc_commit = exports.$Enums.users_qc_commit = {
  QC_COMMIT_NO: 'QC_COMMIT_NO',
  QC_COMMIT_YES: 'QC_COMMIT_YES'
};

exports.users_alter_custphone_override = exports.$Enums.users_alter_custphone_override = {
  Y: 'Y',
  N: 'N'
};

exports.users_active = exports.$Enums.users_active = {
  Y: 'Y',
  N: 'N'
};

exports.users_alert_enabled = exports.$Enums.users_alert_enabled = {
  ALERT_DISABLED: 'ALERT_DISABLED',
  ALERT_ENABLED: 'ALERT_ENABLED'
};

exports.users_agent_shift_enforcement_override = exports.$Enums.users_agent_shift_enforcement_override = {
  DISABLED: 'DISABLED',
  OFF: 'OFF',
  START: 'START',
  ALL: 'ALL'
};

exports.users_manager_shift_enforcement_override = exports.$Enums.users_manager_shift_enforcement_override = {
  SHIFT_OVERRIDE_NO: 'SHIFT_OVERRIDE_NO',
  SHIFT_OVERRIDE_YES: 'SHIFT_OVERRIDE_YES'
};

exports.users_shift_override_flag = exports.$Enums.users_shift_override_flag = {
  SHIFT_OVERRIDE_FLAG_NO: 'SHIFT_OVERRIDE_FLAG_NO',
  SHIFT_OVERRIDE_FLAG_YES: 'SHIFT_OVERRIDE_FLAG_YES'
};

exports.users_default_callback_gmt_selection = exports.$Enums.users_default_callback_gmt_selection = {
  AGENT: 'AGENT',
  LEAD: 'LEAD'
};

exports.users_realtime_listen = exports.$Enums.users_realtime_listen = {
  REALTIME_LISTEN_NO: 'REALTIME_LISTEN_NO',
  REALTIME_LISTEN_YES: 'REALTIME_LISTEN_YES'
};

exports.users_chat_history = exports.$Enums.users_chat_history = {
  CHAT_HISTORY_NO: 'CHAT_HISTORY_NO',
  CHAT_HISTORY_YES: 'CHAT_HISTORY_YES'
};

exports.users_auto_mode = exports.$Enums.users_auto_mode = {
  AUTO_MODE_NO: 'AUTO_MODE_NO',
  AUTO_MODE_YES: 'AUTO_MODE_YES'
};

exports.users_notification = exports.$Enums.users_notification = {
  NOTIFICATION_OFF: 'NOTIFICATION_OFF',
  NOTIFICATION_ON: 'NOTIFICATION_ON'
};

exports.users_connection_type = exports.$Enums.users_connection_type = {
  BROWSER: 'BROWSER',
  EXTERNAL: 'EXTERNAL',
  DIALIN: 'DIALIN',
  SHARED_EXTENSION: 'SHARED_EXTENSION'
};

exports.users_connect_using = exports.$Enums.users_connect_using = {
  LONG_POLLING: 'LONG_POLLING',
  SOCKET: 'SOCKET'
};

exports.users_allow_choose_cid = exports.$Enums.users_allow_choose_cid = {
  YES: 'YES',
  NO: 'NO'
};

exports.users_queue_override = exports.$Enums.users_queue_override = {
  USE_CAMPAIGN: 'USE_CAMPAIGN',
  MATCH: 'MATCH',
  OVERRIDE: 'OVERRIDE',
  COMBINE: 'COMBINE'
};

exports.users_allow_mobile = exports.$Enums.users_allow_mobile = {
  ZERO: 'ZERO',
  ONE: 'ONE'
};

exports.users_alter_override = exports.$Enums.users_alter_override = {
  Y: 'Y',
  N: 'N'
};

exports.users_allow_calling_dnc = exports.$Enums.users_allow_calling_dnc = {
  Y: 'Y',
  N: 'N'
};

exports.users_remote_agent = exports.$Enums.users_remote_agent = {
  N: 'N',
  Y: 'Y',
  V: 'V'
};

exports.Prisma.ModelName = {
  users: 'users'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
