
    export const clusterServer = [
        'cluster_03',
        'cluster_04',
        'cluster_05',
        'cluster_06',
        'cluster_08',
        'cluster_09',
        'cluster_10',
        'cluster_11',
        'cluster_12',
        'cluster_13',
        'cluster_14',
        'cluster_15',
        'cluster_16',
        'cluster_17',
        'cluster_18',
        'cluster_19',
        'cluster_20',
        'cluster_21',
        'cluster_22',
        'cluster_23',
        'cluster_24',
        'cluster_25',
        'cluster_26',
        'cluster_27',
        'cluster_28',
        'cluster_29',
        'cluster_30',
        'cluster_31',
        'cluster_32',
        'cluster_33',
        'cluster_34',
        'cluster_35',
        'cluster_36',
        'cluster_37',
        'cluster_51',
        'cluster_52',
        'cluster_53',
        'cluster_54',
        'cluster_55',
        'cluster_99',
    ];

    export const safesoft_encrypt_decrypt_key:any = process.env.ENCRYPT_KEY;