
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminScalarFieldEnum = {
  variable: 'variable',
  value: 'value'
};

exports.Prisma.AmpusersScalarFieldEnum = {
  username: 'username',
  password_sha1: 'password_sha1',
  extension_low: 'extension_low',
  extension_high: 'extension_high',
  deptname: 'deptname',
  sections: 'sections'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  announcement_id: 'announcement_id',
  description: 'description',
  recording_id: 'recording_id',
  allow_skip: 'allow_skip',
  post_dest: 'post_dest',
  return_ivr: 'return_ivr',
  noanswer: 'noanswer',
  repeat_msg: 'repeat_msg',
  context: 'context'
};

exports.Prisma.BackupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  immortal: 'immortal',
  data: 'data'
};

exports.Prisma.Backup_cacheScalarFieldEnum = {
  id: 'id',
  manifest: 'manifest'
};

exports.Prisma.Backup_detailsScalarFieldEnum = {
  backup_id: 'backup_id',
  key: 'key',
  index: 'index',
  value: 'value',
  uid: 'uid'
};

exports.Prisma.Backup_itemsScalarFieldEnum = {
  backup_id: 'backup_id',
  type: 'type',
  path: 'path',
  exclude: 'exclude',
  uid: 'uid'
};

exports.Prisma.Backup_server_detailsScalarFieldEnum = {
  server_id: 'server_id',
  key: 'key',
  value: 'value',
  uid: 'uid'
};

exports.Prisma.Backup_serversScalarFieldEnum = {
  id: 'id',
  name: 'name',
  desc: 'desc',
  type: 'type',
  readonly: 'readonly',
  immortal: 'immortal',
  data: 'data'
};

exports.Prisma.Backup_template_detailsScalarFieldEnum = {
  template_id: 'template_id',
  type: 'type',
  path: 'path',
  exclude: 'exclude',
  uid: 'uid'
};

exports.Prisma.Backup_templatesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  desc: 'desc',
  immortal: 'immortal',
  data: 'data'
};

exports.Prisma.CallbackScalarFieldEnum = {
  callback_id: 'callback_id',
  description: 'description',
  callbacknum: 'callbacknum',
  destination: 'destination',
  sleep: 'sleep',
  deptname: 'deptname',
  context: 'context'
};

exports.Prisma.CallrecordingScalarFieldEnum = {
  callrecording_id: 'callrecording_id',
  callrecording_mode: 'callrecording_mode',
  description: 'description',
  dest: 'dest'
};

exports.Prisma.Callrecording_moduleScalarFieldEnum = {
  extension: 'extension',
  cidnum: 'cidnum',
  callrecording: 'callrecording',
  display: 'display',
  uid: 'uid'
};

exports.Prisma.CidlookupScalarFieldEnum = {
  cidlookup_id: 'cidlookup_id',
  description: 'description',
  sourcetype: 'sourcetype',
  cache: 'cache',
  deptname: 'deptname',
  http_host: 'http_host',
  http_port: 'http_port',
  http_username: 'http_username',
  http_password: 'http_password',
  http_path: 'http_path',
  http_query: 'http_query',
  mysql_host: 'mysql_host',
  mysql_dbname: 'mysql_dbname',
  mysql_query: 'mysql_query',
  mysql_username: 'mysql_username',
  mysql_password: 'mysql_password',
  mysql_charset: 'mysql_charset',
  opencnam_account_sid: 'opencnam_account_sid',
  opencnam_auth_token: 'opencnam_auth_token'
};

exports.Prisma.Cidlookup_incomingScalarFieldEnum = {
  cidlookup_id: 'cidlookup_id',
  extension: 'extension',
  cidnum: 'cidnum',
  uid: 'uid'
};

exports.Prisma.Contactdir_listScalarFieldEnum = {
  extension: 'extension',
  user_name: 'user_name',
  server_id: 'server_id',
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  email: 'email',
  tel: 'tel',
  tel_spdial: 'tel_spdial',
  home: 'home',
  home_spdial: 'home_spdial',
  mobile: 'mobile',
  mobile_spdial: 'mobile_spdial',
  lastupdate: 'lastupdate',
  mgcbtn: 'mgcbtn',
  grammer: 'grammer'
};

exports.Prisma.Contactdir_server_typesScalarFieldEnum = {
  id: 'id',
  server_type: 'server_type'
};

exports.Prisma.Contactdir_serversScalarFieldEnum = {
  id: 'id',
  server_type: 'server_type',
  display_name: 'display_name',
  host: 'host',
  port: 'port',
  usessl: 'usessl'
};

exports.Prisma.CronmanagerScalarFieldEnum = {
  module: 'module',
  id: 'id',
  time: 'time',
  freq: 'freq',
  lasttime: 'lasttime',
  command: 'command'
};

exports.Prisma.Custom_destinationsScalarFieldEnum = {
  custom_dest: 'custom_dest',
  description: 'description',
  notes: 'notes'
};

exports.Prisma.Custom_extensionsScalarFieldEnum = {
  custom_exten: 'custom_exten',
  description: 'description',
  notes: 'notes'
};

exports.Prisma.DahdiScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data',
  flags: 'flags'
};

exports.Prisma.DahdichandidsScalarFieldEnum = {
  channel: 'channel',
  description: 'description',
  did: 'did'
};

exports.Prisma.DaynightScalarFieldEnum = {
  ext: 'ext',
  dmode: 'dmode',
  dest: 'dest'
};

exports.Prisma.DevicesScalarFieldEnum = {
  id: 'id',
  tech: 'tech',
  dial: 'dial',
  devicetype: 'devicetype',
  user: 'user',
  description: 'description',
  emergency_cid: 'emergency_cid'
};

exports.Prisma.Directory_detailsScalarFieldEnum = {
  id: 'id',
  dirname: 'dirname',
  description: 'description',
  announcement: 'announcement',
  callid_prefix: 'callid_prefix',
  alert_info: 'alert_info',
  repeat_loops: 'repeat_loops',
  repeat_recording: 'repeat_recording',
  invalid_recording: 'invalid_recording',
  invalid_destination: 'invalid_destination',
  retivr: 'retivr',
  say_extension: 'say_extension',
  projectx_global: 'projectx_global'
};

exports.Prisma.Directory_entriesScalarFieldEnum = {
  e_id: 'e_id',
  name: 'name',
  type: 'type',
  foreign_id: 'foreign_id',
  audio: 'audio',
  dial: 'dial',
  id: 'id',
  uid: 'uid'
};

exports.Prisma.ExtensionsScalarFieldEnum = {
  context: 'context',
  extension: 'extension',
  priority: 'priority',
  application: 'application',
  args: 'args',
  descr: 'descr',
  flags: 'flags'
};

exports.Prisma.Fax_detailsScalarFieldEnum = {
  key: 'key',
  value: 'value',
  uid: 'uid'
};

exports.Prisma.Fax_incomingScalarFieldEnum = {
  cidnum: 'cidnum',
  extension: 'extension',
  detection: 'detection',
  detectionwait: 'detectionwait',
  destination: 'destination',
  legacy_email: 'legacy_email',
  uid: 'uid'
};

exports.Prisma.Fax_usersScalarFieldEnum = {
  user: 'user',
  faxenabled: 'faxenabled',
  faxemail: 'faxemail',
  faxattachformat: 'faxattachformat'
};

exports.Prisma.FeaturecodesScalarFieldEnum = {
  modulename: 'modulename',
  featurename: 'featurename',
  description: 'description',
  defaultcode: 'defaultcode',
  customcode: 'customcode',
  enabled: 'enabled',
  providedest: 'providedest'
};

exports.Prisma.FindmefollowScalarFieldEnum = {
  grpnum: 'grpnum',
  strategy: 'strategy',
  grptime: 'grptime',
  grppre: 'grppre',
  grplist: 'grplist',
  annmsg_id: 'annmsg_id',
  postdest: 'postdest',
  dring: 'dring',
  remotealert_id: 'remotealert_id',
  needsconf: 'needsconf',
  toolate_id: 'toolate_id',
  pre_ring: 'pre_ring',
  ringing: 'ringing'
};

exports.Prisma.Freepbx_logScalarFieldEnum = {
  id: 'id',
  time: 'time',
  section: 'section',
  level: 'level',
  status: 'status',
  message: 'message'
};

exports.Prisma.Freepbx_settingsScalarFieldEnum = {
  keyword: 'keyword',
  value: 'value',
  name: 'name',
  level: 'level',
  description: 'description',
  type: 'type',
  options: 'options',
  defaultval: 'defaultval',
  readonly: 'readonly',
  hidden: 'hidden',
  category: 'category',
  module: 'module',
  emptyok: 'emptyok',
  sortorder: 'sortorder'
};

exports.Prisma.Freepbx_usersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  description: 'description',
  password: 'password',
  default_extension: 'default_extension',
  fname: 'fname',
  lname: 'lname',
  title: 'title',
  department: 'department',
  email: 'email',
  cell: 'cell',
  work: 'work',
  home: 'home'
};

exports.Prisma.Freepbx_users_settingsScalarFieldEnum = {
  uid: 'uid',
  module: 'module',
  key: 'key',
  val: 'val',
  type: 'type'
};

exports.Prisma.GlobalsScalarFieldEnum = {
  variable: 'variable',
  value: 'value'
};

exports.Prisma.HotelwakeupScalarFieldEnum = {
  maxretries: 'maxretries',
  waittime: 'waittime',
  retrytime: 'retrytime',
  extensionlength: 'extensionlength',
  cid: 'cid',
  cnam: 'cnam',
  operator_mode: 'operator_mode',
  operator_extensions: 'operator_extensions',
  application: 'application',
  data: 'data'
};

exports.Prisma.Hotelwakeup_callsScalarFieldEnum = {
  time: 'time',
  ext: 'ext',
  maxretries: 'maxretries',
  retrytime: 'retrytime',
  waittime: 'waittime',
  cid: 'cid',
  cnam: 'cnam',
  application: 'application',
  data: 'data',
  tempdir: 'tempdir',
  outdir: 'outdir',
  filename: 'filename',
  frequency: 'frequency'
};

exports.Prisma.IaxScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data',
  flags: 'flags'
};

exports.Prisma.IaxsettingsScalarFieldEnum = {
  keyword: 'keyword',
  data: 'data',
  seq: 'seq',
  type: 'type'
};

exports.Prisma.IncomingScalarFieldEnum = {
  cidnum: 'cidnum',
  extension: 'extension',
  destination: 'destination',
  faxexten: 'faxexten',
  faxemail: 'faxemail',
  answer: 'answer',
  wait: 'wait',
  privacyman: 'privacyman',
  alertinfo: 'alertinfo',
  ringing: 'ringing',
  mohclass: 'mohclass',
  description: 'description',
  grppre: 'grppre',
  delay_answer: 'delay_answer',
  pricid: 'pricid',
  pmmaxretries: 'pmmaxretries',
  pmminlength: 'pmminlength'
};

exports.Prisma.Indications_zonelistScalarFieldEnum = {
  name: 'name',
  iso: 'iso',
  conf: 'conf'
};

exports.Prisma.Ivr_detailsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  announcement: 'announcement',
  directdial: 'directdial',
  invalid_loops: 'invalid_loops',
  invalid_retry_recording: 'invalid_retry_recording',
  invalid_destination: 'invalid_destination',
  invalid_recording: 'invalid_recording',
  retvm: 'retvm',
  timeout_time: 'timeout_time',
  timeout_recording: 'timeout_recording',
  timeout_retry_recording: 'timeout_retry_recording',
  timeout_destination: 'timeout_destination',
  timeout_loops: 'timeout_loops',
  timeout_append_announce: 'timeout_append_announce',
  invalid_append_announce: 'invalid_append_announce'
};

exports.Prisma.Logfile_logfilesScalarFieldEnum = {
  name: 'name',
  debug: 'debug',
  dtmf: 'dtmf',
  error: 'error',
  fax: 'fax',
  notice: 'notice',
  verbose: 'verbose',
  warning: 'warning',
  security: 'security'
};

exports.Prisma.Logfile_settingsScalarFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.ManagerScalarFieldEnum = {
  manager_id: 'manager_id',
  name: 'name',
  secret: 'secret',
  deny: 'deny',
  permit: 'permit',
  read: 'read',
  write: 'write'
};

exports.Prisma.MeetmeScalarFieldEnum = {
  exten: 'exten',
  options: 'options',
  userpin: 'userpin',
  adminpin: 'adminpin',
  description: 'description',
  joinmsg_id: 'joinmsg_id',
  music: 'music',
  users: 'users',
  uid: 'uid',
  context: 'context'
};

exports.Prisma.MiscappsScalarFieldEnum = {
  miscapps_id: 'miscapps_id',
  ext: 'ext',
  description: 'description',
  dest: 'dest'
};

exports.Prisma.MiscdestsScalarFieldEnum = {
  id: 'id',
  description: 'description',
  destdial: 'destdial',
  context: 'context'
};

exports.Prisma.Module_xmlScalarFieldEnum = {
  id: 'id',
  time: 'time',
  data: 'data'
};

exports.Prisma.ModulesScalarFieldEnum = {
  id: 'id',
  modulename: 'modulename',
  version: 'version',
  enabled: 'enabled'
};

exports.Prisma.NotificationsScalarFieldEnum = {
  module: 'module',
  id: 'id',
  level: 'level',
  display_text: 'display_text',
  extended_text: 'extended_text',
  link: 'link',
  reset: 'reset',
  candelete: 'candelete',
  timestamp: 'timestamp'
};

exports.Prisma.Outbound_route_patternsScalarFieldEnum = {
  route_id: 'route_id',
  match_pattern_prefix: 'match_pattern_prefix',
  match_pattern_pass: 'match_pattern_pass',
  match_cid: 'match_cid',
  prepend_digits: 'prepend_digits'
};

exports.Prisma.Outbound_route_sequenceScalarFieldEnum = {
  route_id: 'route_id',
  seq: 'seq'
};

exports.Prisma.Outbound_route_trunksScalarFieldEnum = {
  route_id: 'route_id',
  trunk_id: 'trunk_id',
  seq: 'seq'
};

exports.Prisma.Outbound_routesScalarFieldEnum = {
  route_id: 'route_id',
  name: 'name',
  outcid: 'outcid',
  outcid_mode: 'outcid_mode',
  password: 'password',
  emergency_route: 'emergency_route',
  intracompany_route: 'intracompany_route',
  mohclass: 'mohclass',
  time_group_id: 'time_group_id',
  dest: 'dest'
};

exports.Prisma.OutroutemsgScalarFieldEnum = {
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.Paging_autoanswerScalarFieldEnum = {
  useragent: 'useragent',
  var: 'var',
  setting: 'setting'
};

exports.Prisma.Paging_configScalarFieldEnum = {
  page_group: 'page_group',
  force_page: 'force_page',
  duplex: 'duplex',
  description: 'description'
};

exports.Prisma.Paging_groupsScalarFieldEnum = {
  page_number: 'page_number',
  ext: 'ext'
};

exports.Prisma.ParkplusScalarFieldEnum = {
  id: 'id',
  defaultlot: 'defaultlot',
  type: 'type',
  name: 'name',
  parkext: 'parkext',
  parkpos: 'parkpos',
  numslots: 'numslots',
  parkingtime: 'parkingtime',
  parkedmusicclass: 'parkedmusicclass',
  generatefc: 'generatefc',
  generatehints: 'generatehints',
  findslot: 'findslot',
  parkedplay: 'parkedplay',
  parkedcalltransfers: 'parkedcalltransfers',
  parkedcallreparking: 'parkedcallreparking',
  alertinfo: 'alertinfo',
  cidpp: 'cidpp',
  autocidpp: 'autocidpp',
  announcement_id: 'announcement_id',
  comebacktoorigin: 'comebacktoorigin',
  dest: 'dest'
};

exports.Prisma.Pinset_usageScalarFieldEnum = {
  pinsets_id: 'pinsets_id',
  dispname: 'dispname',
  foreign_id: 'foreign_id'
};

exports.Prisma.PinsetsScalarFieldEnum = {
  pinsets_id: 'pinsets_id',
  passwords: 'passwords',
  description: 'description',
  addtocdr: 'addtocdr',
  deptname: 'deptname'
};

exports.Prisma.Presencestate_listScalarFieldEnum = {
  id: 'id',
  type: 'type',
  message: 'message'
};

exports.Prisma.Presencestate_prefsScalarFieldEnum = {
  extension: 'extension',
  item_id: 'item_id',
  pref: 'pref'
};

exports.Prisma.QueueprioScalarFieldEnum = {
  queueprio_id: 'queueprio_id',
  queue_priority: 'queue_priority',
  description: 'description',
  dest: 'dest',
  context: 'context'
};

exports.Prisma.Queues_configScalarFieldEnum = {
  extension: 'extension',
  descr: 'descr',
  grppre: 'grppre',
  alertinfo: 'alertinfo',
  ringing: 'ringing',
  maxwait: 'maxwait',
  password: 'password',
  ivr_id: 'ivr_id',
  dest: 'dest',
  cwignore: 'cwignore',
  queuewait: 'queuewait',
  use_queue_context: 'use_queue_context',
  togglehint: 'togglehint',
  qnoanswer: 'qnoanswer',
  callconfirm: 'callconfirm',
  callconfirm_id: 'callconfirm_id',
  qregex: 'qregex',
  agentannounce_id: 'agentannounce_id',
  joinannounce_id: 'joinannounce_id',
  monitor_type: 'monitor_type',
  monitor_heard: 'monitor_heard',
  monitor_spoken: 'monitor_spoken'
};

exports.Prisma.Queues_detailsScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data',
  flags: 'flags'
};

exports.Prisma.RecordingsScalarFieldEnum = {
  id: 'id',
  displayname: 'displayname',
  filename: 'filename',
  description: 'description',
  fcode: 'fcode',
  fcode_pass: 'fcode_pass'
};

exports.Prisma.RinggroupsScalarFieldEnum = {
  grpnum: 'grpnum',
  strategy: 'strategy',
  grptime: 'grptime',
  grppre: 'grppre',
  grplist: 'grplist',
  annmsg_id: 'annmsg_id',
  postdest: 'postdest',
  description: 'description',
  alertinfo: 'alertinfo',
  remotealert_id: 'remotealert_id',
  needsconf: 'needsconf',
  toolate_id: 'toolate_id',
  ringing: 'ringing',
  cwignore: 'cwignore',
  cfignore: 'cfignore',
  cpickup: 'cpickup',
  recording: 'recording'
};

exports.Prisma.SetcidScalarFieldEnum = {
  cid_id: 'cid_id',
  cid_name: 'cid_name',
  cid_num: 'cid_num',
  description: 'description',
  dest: 'dest'
};

exports.Prisma.SipScalarFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data',
  flags: 'flags'
};

exports.Prisma.SipsettingsScalarFieldEnum = {
  keyword: 'keyword',
  data: 'data',
  seq: 'seq',
  type: 'type'
};

exports.Prisma.TimeconditionsScalarFieldEnum = {
  timeconditions_id: 'timeconditions_id',
  displayname: 'displayname',
  time: 'time',
  truegoto: 'truegoto',
  falsegoto: 'falsegoto',
  deptname: 'deptname',
  generate_hint: 'generate_hint',
  priority: 'priority',
  context: 'context'
};

exports.Prisma.Timegroups_detailsScalarFieldEnum = {
  id: 'id',
  timegroupid: 'timegroupid',
  time: 'time'
};

exports.Prisma.Timegroups_groupsScalarFieldEnum = {
  id: 'id',
  description: 'description',
  context: 'context'
};

exports.Prisma.Trunk_dialpatternsScalarFieldEnum = {
  trunkid: 'trunkid',
  match_pattern_prefix: 'match_pattern_prefix',
  match_pattern_pass: 'match_pattern_pass',
  prepend_digits: 'prepend_digits',
  seq: 'seq'
};

exports.Prisma.TrunksScalarFieldEnum = {
  trunkid: 'trunkid',
  name: 'name',
  tech: 'tech',
  outcid: 'outcid',
  keepcid: 'keepcid',
  maxchans: 'maxchans',
  failscript: 'failscript',
  dialoutprefix: 'dialoutprefix',
  channelid: 'channelid',
  usercontext: 'usercontext',
  provider: 'provider',
  disabled: 'disabled',
  continue: 'continue'
};

exports.Prisma.TtsenginesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  path: 'path'
};

exports.Prisma.UsersScalarFieldEnum = {
  extension: 'extension',
  password: 'password',
  name: 'name',
  voicemail: 'voicemail',
  ringtimer: 'ringtimer',
  noanswer: 'noanswer',
  recording: 'recording',
  outboundcid: 'outboundcid',
  sipname: 'sipname',
  noanswer_cid: 'noanswer_cid',
  busy_cid: 'busy_cid',
  chanunavail_cid: 'chanunavail_cid',
  noanswer_dest: 'noanswer_dest',
  busy_dest: 'busy_dest',
  chanunavail_dest: 'chanunavail_dest',
  mohclass: 'mohclass',
  uid: 'uid'
};

exports.Prisma.VmblastScalarFieldEnum = {
  grpnum: 'grpnum',
  description: 'description',
  audio_label: 'audio_label',
  password: 'password'
};

exports.Prisma.Vmblast_groupsScalarFieldEnum = {
  grpnum: 'grpnum',
  ext: 'ext'
};

exports.Prisma.Voicemail_adminScalarFieldEnum = {
  variable: 'variable',
  value: 'value'
};

exports.Prisma.Webrtc_clientsScalarFieldEnum = {
  user: 'user',
  device: 'device',
  realm: 'realm',
  username: 'username',
  sipuri: 'sipuri',
  password: 'password',
  websocket: 'websocket',
  breaker: 'breaker',
  cid: 'cid',
  uid: 'uid'
};

exports.Prisma.Webrtc_settingsScalarFieldEnum = {
  key: 'key',
  value: 'value',
  uid: 'uid'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.adminOrderByRelevanceFieldEnum = {
  variable: 'variable',
  value: 'value'
};

exports.Prisma.ampusersOrderByRelevanceFieldEnum = {
  username: 'username',
  password_sha1: 'password_sha1',
  extension_low: 'extension_low',
  extension_high: 'extension_high',
  deptname: 'deptname'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.announcementOrderByRelevanceFieldEnum = {
  description: 'description',
  post_dest: 'post_dest',
  repeat_msg: 'repeat_msg',
  context: 'context'
};

exports.Prisma.backupOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description',
  immortal: 'immortal',
  data: 'data'
};

exports.Prisma.backup_cacheOrderByRelevanceFieldEnum = {
  id: 'id',
  manifest: 'manifest'
};

exports.Prisma.backup_detailsOrderByRelevanceFieldEnum = {
  key: 'key',
  index: 'index',
  value: 'value'
};

exports.Prisma.backup_itemsOrderByRelevanceFieldEnum = {
  type: 'type',
  path: 'path',
  exclude: 'exclude'
};

exports.Prisma.backup_server_detailsOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.backup_serversOrderByRelevanceFieldEnum = {
  name: 'name',
  desc: 'desc',
  type: 'type',
  readonly: 'readonly',
  immortal: 'immortal',
  data: 'data'
};

exports.Prisma.backup_template_detailsOrderByRelevanceFieldEnum = {
  type: 'type',
  path: 'path',
  exclude: 'exclude'
};

exports.Prisma.backup_templatesOrderByRelevanceFieldEnum = {
  name: 'name',
  desc: 'desc',
  immortal: 'immortal',
  data: 'data'
};

exports.Prisma.callbackOrderByRelevanceFieldEnum = {
  description: 'description',
  callbacknum: 'callbacknum',
  destination: 'destination',
  deptname: 'deptname',
  context: 'context'
};

exports.Prisma.callrecordingOrderByRelevanceFieldEnum = {
  callrecording_mode: 'callrecording_mode',
  description: 'description',
  dest: 'dest'
};

exports.Prisma.callrecording_moduleOrderByRelevanceFieldEnum = {
  extension: 'extension',
  cidnum: 'cidnum',
  callrecording: 'callrecording',
  display: 'display'
};

exports.Prisma.cidlookupOrderByRelevanceFieldEnum = {
  description: 'description',
  sourcetype: 'sourcetype',
  deptname: 'deptname',
  http_host: 'http_host',
  http_port: 'http_port',
  http_username: 'http_username',
  http_password: 'http_password',
  http_path: 'http_path',
  http_query: 'http_query',
  mysql_host: 'mysql_host',
  mysql_dbname: 'mysql_dbname',
  mysql_query: 'mysql_query',
  mysql_username: 'mysql_username',
  mysql_password: 'mysql_password',
  mysql_charset: 'mysql_charset',
  opencnam_account_sid: 'opencnam_account_sid',
  opencnam_auth_token: 'opencnam_auth_token'
};

exports.Prisma.cidlookup_incomingOrderByRelevanceFieldEnum = {
  extension: 'extension',
  cidnum: 'cidnum'
};

exports.Prisma.contactdir_listOrderByRelevanceFieldEnum = {
  extension: 'extension',
  user_name: 'user_name',
  server_id: 'server_id',
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  email: 'email',
  tel: 'tel',
  tel_spdial: 'tel_spdial',
  home: 'home',
  home_spdial: 'home_spdial',
  mobile: 'mobile',
  mobile_spdial: 'mobile_spdial',
  lastupdate: 'lastupdate',
  mgcbtn: 'mgcbtn',
  grammer: 'grammer'
};

exports.Prisma.contactdir_server_typesOrderByRelevanceFieldEnum = {
  server_type: 'server_type'
};

exports.Prisma.contactdir_serversOrderByRelevanceFieldEnum = {
  display_name: 'display_name',
  host: 'host',
  port: 'port'
};

exports.Prisma.cronmanagerOrderByRelevanceFieldEnum = {
  module: 'module',
  id: 'id',
  time: 'time',
  command: 'command'
};

exports.Prisma.custom_destinationsOrderByRelevanceFieldEnum = {
  custom_dest: 'custom_dest',
  description: 'description',
  notes: 'notes'
};

exports.Prisma.custom_extensionsOrderByRelevanceFieldEnum = {
  custom_exten: 'custom_exten',
  description: 'description',
  notes: 'notes'
};

exports.Prisma.dahdiOrderByRelevanceFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.dahdichandidsOrderByRelevanceFieldEnum = {
  description: 'description',
  did: 'did'
};

exports.Prisma.daynightOrderByRelevanceFieldEnum = {
  ext: 'ext',
  dmode: 'dmode',
  dest: 'dest'
};

exports.Prisma.devicesOrderByRelevanceFieldEnum = {
  id: 'id',
  tech: 'tech',
  dial: 'dial',
  devicetype: 'devicetype',
  user: 'user',
  description: 'description',
  emergency_cid: 'emergency_cid'
};

exports.Prisma.directory_detailsOrderByRelevanceFieldEnum = {
  dirname: 'dirname',
  description: 'description',
  callid_prefix: 'callid_prefix',
  alert_info: 'alert_info',
  repeat_loops: 'repeat_loops',
  invalid_destination: 'invalid_destination',
  retivr: 'retivr',
  say_extension: 'say_extension'
};

exports.Prisma.directory_entriesOrderByRelevanceFieldEnum = {
  name: 'name',
  type: 'type',
  foreign_id: 'foreign_id',
  audio: 'audio',
  dial: 'dial'
};

exports.Prisma.extensionsOrderByRelevanceFieldEnum = {
  context: 'context',
  extension: 'extension',
  priority: 'priority',
  application: 'application',
  args: 'args',
  descr: 'descr'
};

exports.Prisma.fax_detailsOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.fax_incomingOrderByRelevanceFieldEnum = {
  cidnum: 'cidnum',
  extension: 'extension',
  detection: 'detection',
  detectionwait: 'detectionwait',
  destination: 'destination',
  legacy_email: 'legacy_email'
};

exports.Prisma.fax_usersOrderByRelevanceFieldEnum = {
  user: 'user',
  faxenabled: 'faxenabled',
  faxemail: 'faxemail',
  faxattachformat: 'faxattachformat'
};

exports.Prisma.featurecodesOrderByRelevanceFieldEnum = {
  modulename: 'modulename',
  featurename: 'featurename',
  description: 'description',
  defaultcode: 'defaultcode',
  customcode: 'customcode'
};

exports.Prisma.findmefollowOrderByRelevanceFieldEnum = {
  grpnum: 'grpnum',
  strategy: 'strategy',
  grppre: 'grppre',
  grplist: 'grplist',
  postdest: 'postdest',
  dring: 'dring',
  needsconf: 'needsconf',
  ringing: 'ringing'
};

exports.Prisma.freepbx_logOrderByRelevanceFieldEnum = {
  section: 'section',
  message: 'message'
};

exports.Prisma.freepbx_settingsOrderByRelevanceFieldEnum = {
  keyword: 'keyword',
  value: 'value',
  name: 'name',
  description: 'description',
  type: 'type',
  options: 'options',
  defaultval: 'defaultval',
  category: 'category',
  module: 'module'
};

exports.Prisma.freepbx_usersOrderByRelevanceFieldEnum = {
  username: 'username',
  description: 'description',
  password: 'password',
  default_extension: 'default_extension',
  fname: 'fname',
  lname: 'lname',
  title: 'title',
  department: 'department',
  email: 'email',
  cell: 'cell',
  work: 'work',
  home: 'home'
};

exports.Prisma.freepbx_users_settingsOrderByRelevanceFieldEnum = {
  module: 'module',
  key: 'key',
  type: 'type'
};

exports.Prisma.globalsOrderByRelevanceFieldEnum = {
  variable: 'variable',
  value: 'value'
};

exports.Prisma.hotelwakeupOrderByRelevanceFieldEnum = {
  cid: 'cid',
  cnam: 'cnam',
  operator_extensions: 'operator_extensions',
  application: 'application',
  data: 'data'
};

exports.Prisma.hotelwakeup_callsOrderByRelevanceFieldEnum = {
  cid: 'cid',
  cnam: 'cnam',
  application: 'application',
  data: 'data',
  tempdir: 'tempdir',
  outdir: 'outdir',
  filename: 'filename'
};

exports.Prisma.iaxOrderByRelevanceFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.iaxsettingsOrderByRelevanceFieldEnum = {
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.incomingOrderByRelevanceFieldEnum = {
  cidnum: 'cidnum',
  extension: 'extension',
  destination: 'destination',
  faxexten: 'faxexten',
  faxemail: 'faxemail',
  alertinfo: 'alertinfo',
  ringing: 'ringing',
  mohclass: 'mohclass',
  description: 'description',
  grppre: 'grppre',
  pricid: 'pricid',
  pmmaxretries: 'pmmaxretries',
  pmminlength: 'pmminlength'
};

exports.Prisma.indications_zonelistOrderByRelevanceFieldEnum = {
  name: 'name',
  iso: 'iso'
};

exports.Prisma.ivr_detailsOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description',
  directdial: 'directdial',
  invalid_loops: 'invalid_loops',
  invalid_retry_recording: 'invalid_retry_recording',
  invalid_destination: 'invalid_destination',
  invalid_recording: 'invalid_recording',
  retvm: 'retvm',
  timeout_recording: 'timeout_recording',
  timeout_retry_recording: 'timeout_retry_recording',
  timeout_destination: 'timeout_destination',
  timeout_loops: 'timeout_loops'
};

exports.Prisma.logfile_logfilesOrderByRelevanceFieldEnum = {
  name: 'name',
  debug: 'debug',
  dtmf: 'dtmf',
  error: 'error',
  fax: 'fax',
  notice: 'notice',
  verbose: 'verbose',
  warning: 'warning',
  security: 'security'
};

exports.Prisma.logfile_settingsOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.managerOrderByRelevanceFieldEnum = {
  name: 'name',
  secret: 'secret',
  deny: 'deny',
  permit: 'permit',
  read: 'read',
  write: 'write'
};

exports.Prisma.meetmeOrderByRelevanceFieldEnum = {
  exten: 'exten',
  options: 'options',
  userpin: 'userpin',
  adminpin: 'adminpin',
  description: 'description',
  music: 'music',
  context: 'context'
};

exports.Prisma.miscappsOrderByRelevanceFieldEnum = {
  ext: 'ext',
  description: 'description',
  dest: 'dest'
};

exports.Prisma.miscdestsOrderByRelevanceFieldEnum = {
  description: 'description',
  destdial: 'destdial',
  context: 'context'
};

exports.Prisma.module_xmlOrderByRelevanceFieldEnum = {
  id: 'id'
};

exports.Prisma.modulesOrderByRelevanceFieldEnum = {
  modulename: 'modulename',
  version: 'version'
};

exports.Prisma.notificationsOrderByRelevanceFieldEnum = {
  module: 'module',
  id: 'id',
  display_text: 'display_text',
  link: 'link'
};

exports.Prisma.outbound_route_patternsOrderByRelevanceFieldEnum = {
  match_pattern_prefix: 'match_pattern_prefix',
  match_pattern_pass: 'match_pattern_pass',
  match_cid: 'match_cid',
  prepend_digits: 'prepend_digits'
};

exports.Prisma.outbound_routesOrderByRelevanceFieldEnum = {
  name: 'name',
  outcid: 'outcid',
  outcid_mode: 'outcid_mode',
  password: 'password',
  emergency_route: 'emergency_route',
  intracompany_route: 'intracompany_route',
  mohclass: 'mohclass',
  dest: 'dest'
};

exports.Prisma.outroutemsgOrderByRelevanceFieldEnum = {
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.paging_autoanswerOrderByRelevanceFieldEnum = {
  useragent: 'useragent',
  var: 'var',
  setting: 'setting'
};

exports.Prisma.paging_configOrderByRelevanceFieldEnum = {
  page_group: 'page_group',
  description: 'description'
};

exports.Prisma.paging_groupsOrderByRelevanceFieldEnum = {
  page_number: 'page_number',
  ext: 'ext'
};

exports.Prisma.parkplusOrderByRelevanceFieldEnum = {
  defaultlot: 'defaultlot',
  type: 'type',
  name: 'name',
  parkext: 'parkext',
  parkpos: 'parkpos',
  parkedmusicclass: 'parkedmusicclass',
  generatefc: 'generatefc',
  generatehints: 'generatehints',
  findslot: 'findslot',
  parkedplay: 'parkedplay',
  parkedcalltransfers: 'parkedcalltransfers',
  parkedcallreparking: 'parkedcallreparking',
  alertinfo: 'alertinfo',
  cidpp: 'cidpp',
  autocidpp: 'autocidpp',
  comebacktoorigin: 'comebacktoorigin',
  dest: 'dest'
};

exports.Prisma.pinset_usageOrderByRelevanceFieldEnum = {
  dispname: 'dispname',
  foreign_id: 'foreign_id'
};

exports.Prisma.pinsetsOrderByRelevanceFieldEnum = {
  passwords: 'passwords',
  description: 'description',
  deptname: 'deptname'
};

exports.Prisma.presencestate_listOrderByRelevanceFieldEnum = {
  type: 'type',
  message: 'message'
};

exports.Prisma.presencestate_prefsOrderByRelevanceFieldEnum = {
  extension: 'extension',
  pref: 'pref'
};

exports.Prisma.queueprioOrderByRelevanceFieldEnum = {
  queue_priority: 'queue_priority',
  description: 'description',
  dest: 'dest',
  context: 'context'
};

exports.Prisma.queues_configOrderByRelevanceFieldEnum = {
  extension: 'extension',
  descr: 'descr',
  grppre: 'grppre',
  alertinfo: 'alertinfo',
  maxwait: 'maxwait',
  password: 'password',
  ivr_id: 'ivr_id',
  dest: 'dest',
  qregex: 'qregex',
  monitor_type: 'monitor_type'
};

exports.Prisma.queues_detailsOrderByRelevanceFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.recordingsOrderByRelevanceFieldEnum = {
  displayname: 'displayname',
  description: 'description',
  fcode_pass: 'fcode_pass'
};

exports.Prisma.ringgroupsOrderByRelevanceFieldEnum = {
  grpnum: 'grpnum',
  strategy: 'strategy',
  grppre: 'grppre',
  grplist: 'grplist',
  postdest: 'postdest',
  description: 'description',
  alertinfo: 'alertinfo',
  needsconf: 'needsconf',
  ringing: 'ringing',
  cwignore: 'cwignore',
  cfignore: 'cfignore',
  cpickup: 'cpickup',
  recording: 'recording'
};

exports.Prisma.setcidOrderByRelevanceFieldEnum = {
  cid_name: 'cid_name',
  cid_num: 'cid_num',
  description: 'description',
  dest: 'dest'
};

exports.Prisma.sipOrderByRelevanceFieldEnum = {
  id: 'id',
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.sipsettingsOrderByRelevanceFieldEnum = {
  keyword: 'keyword',
  data: 'data'
};

exports.Prisma.timeconditionsOrderByRelevanceFieldEnum = {
  displayname: 'displayname',
  truegoto: 'truegoto',
  falsegoto: 'falsegoto',
  deptname: 'deptname',
  priority: 'priority',
  context: 'context'
};

exports.Prisma.timegroups_detailsOrderByRelevanceFieldEnum = {
  time: 'time'
};

exports.Prisma.timegroups_groupsOrderByRelevanceFieldEnum = {
  description: 'description',
  context: 'context'
};

exports.Prisma.trunk_dialpatternsOrderByRelevanceFieldEnum = {
  match_pattern_prefix: 'match_pattern_prefix',
  match_pattern_pass: 'match_pattern_pass',
  prepend_digits: 'prepend_digits'
};

exports.Prisma.trunksOrderByRelevanceFieldEnum = {
  name: 'name',
  tech: 'tech',
  outcid: 'outcid',
  keepcid: 'keepcid',
  maxchans: 'maxchans',
  failscript: 'failscript',
  dialoutprefix: 'dialoutprefix',
  channelid: 'channelid',
  usercontext: 'usercontext',
  provider: 'provider',
  disabled: 'disabled',
  continue: 'continue'
};

exports.Prisma.ttsenginesOrderByRelevanceFieldEnum = {
  name: 'name',
  path: 'path'
};

exports.Prisma.usersOrderByRelevanceFieldEnum = {
  extension: 'extension',
  password: 'password',
  name: 'name',
  voicemail: 'voicemail',
  noanswer: 'noanswer',
  recording: 'recording',
  outboundcid: 'outboundcid',
  sipname: 'sipname',
  noanswer_cid: 'noanswer_cid',
  busy_cid: 'busy_cid',
  chanunavail_cid: 'chanunavail_cid',
  noanswer_dest: 'noanswer_dest',
  busy_dest: 'busy_dest',
  chanunavail_dest: 'chanunavail_dest',
  mohclass: 'mohclass'
};

exports.Prisma.vmblastOrderByRelevanceFieldEnum = {
  description: 'description',
  password: 'password'
};

exports.Prisma.vmblast_groupsOrderByRelevanceFieldEnum = {
  grpnum: 'grpnum',
  ext: 'ext'
};

exports.Prisma.voicemail_adminOrderByRelevanceFieldEnum = {
  variable: 'variable',
  value: 'value'
};

exports.Prisma.webrtc_clientsOrderByRelevanceFieldEnum = {
  user: 'user',
  device: 'device',
  realm: 'realm',
  username: 'username',
  sipuri: 'sipuri',
  password: 'password',
  websocket: 'websocket',
  breaker: 'breaker',
  cid: 'cid'
};

exports.Prisma.webrtc_settingsOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
};
exports.directory_details_projectx_global = exports.$Enums.directory_details_projectx_global = {
  ZERO: 'ZERO',
  ONE: 'ONE'
};

exports.freepbx_log_level = exports.$Enums.freepbx_log_level = {
  error: 'error',
  warning: 'warning',
  debug: 'debug',
  devel_debug: 'devel_debug'
};

exports.Prisma.ModelName = {
  admin: 'admin',
  ampusers: 'ampusers',
  announcement: 'announcement',
  backup: 'backup',
  backup_cache: 'backup_cache',
  backup_details: 'backup_details',
  backup_items: 'backup_items',
  backup_server_details: 'backup_server_details',
  backup_servers: 'backup_servers',
  backup_template_details: 'backup_template_details',
  backup_templates: 'backup_templates',
  callback: 'callback',
  callrecording: 'callrecording',
  callrecording_module: 'callrecording_module',
  cidlookup: 'cidlookup',
  cidlookup_incoming: 'cidlookup_incoming',
  contactdir_list: 'contactdir_list',
  contactdir_server_types: 'contactdir_server_types',
  contactdir_servers: 'contactdir_servers',
  cronmanager: 'cronmanager',
  custom_destinations: 'custom_destinations',
  custom_extensions: 'custom_extensions',
  dahdi: 'dahdi',
  dahdichandids: 'dahdichandids',
  daynight: 'daynight',
  devices: 'devices',
  directory_details: 'directory_details',
  directory_entries: 'directory_entries',
  extensions: 'extensions',
  fax_details: 'fax_details',
  fax_incoming: 'fax_incoming',
  fax_users: 'fax_users',
  featurecodes: 'featurecodes',
  findmefollow: 'findmefollow',
  freepbx_log: 'freepbx_log',
  freepbx_settings: 'freepbx_settings',
  freepbx_users: 'freepbx_users',
  freepbx_users_settings: 'freepbx_users_settings',
  globals: 'globals',
  hotelwakeup: 'hotelwakeup',
  hotelwakeup_calls: 'hotelwakeup_calls',
  iax: 'iax',
  iaxsettings: 'iaxsettings',
  incoming: 'incoming',
  indications_zonelist: 'indications_zonelist',
  ivr_details: 'ivr_details',
  logfile_logfiles: 'logfile_logfiles',
  logfile_settings: 'logfile_settings',
  manager: 'manager',
  meetme: 'meetme',
  miscapps: 'miscapps',
  miscdests: 'miscdests',
  module_xml: 'module_xml',
  modules: 'modules',
  notifications: 'notifications',
  outbound_route_patterns: 'outbound_route_patterns',
  outbound_route_sequence: 'outbound_route_sequence',
  outbound_route_trunks: 'outbound_route_trunks',
  outbound_routes: 'outbound_routes',
  outroutemsg: 'outroutemsg',
  paging_autoanswer: 'paging_autoanswer',
  paging_config: 'paging_config',
  paging_groups: 'paging_groups',
  parkplus: 'parkplus',
  pinset_usage: 'pinset_usage',
  pinsets: 'pinsets',
  presencestate_list: 'presencestate_list',
  presencestate_prefs: 'presencestate_prefs',
  queueprio: 'queueprio',
  queues_config: 'queues_config',
  queues_details: 'queues_details',
  recordings: 'recordings',
  ringgroups: 'ringgroups',
  setcid: 'setcid',
  sip: 'sip',
  sipsettings: 'sipsettings',
  timeconditions: 'timeconditions',
  timegroups_details: 'timegroups_details',
  timegroups_groups: 'timegroups_groups',
  trunk_dialpatterns: 'trunk_dialpatterns',
  trunks: 'trunks',
  ttsengines: 'ttsengines',
  users: 'users',
  vmblast: 'vmblast',
  vmblast_groups: 'vmblast_groups',
  voicemail_admin: 'voicemail_admin',
  webrtc_clients: 'webrtc_clients',
  webrtc_settings: 'webrtc_settings'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
