
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  external_account_id: 'external_account_id',
  name: 'name',
  company_name: 'company_name',
  address: 'address',
  address_2: 'address_2',
  city: 'city',
  state: 'state',
  zipcode: 'zipcode',
  country: 'country',
  phone: 'phone',
  website: 'website',
  local_gmt: 'local_gmt',
  cluster_node: 'cluster_node',
  site_id: 'site_id',
  billing_id: 'billing_id',
  status: 'status',
  impersonate_key: 'impersonate_key',
  impersonate_expired_at: 'impersonate_expired_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Acl_access_profileScalarFieldEnum = {
  id: 'id',
  profile_id: 'profile_id',
  section_name: 'section_name',
  allow_read: 'allow_read',
  allow_write: 'allow_write',
  allow_delete: 'allow_delete',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  account_id: 'account_id'
};

exports.Prisma.Acl_access_profile_mainScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  account_id: 'account_id'
};

exports.Prisma.AssetsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  type: 'type',
  original_filename: 'original_filename',
  original_extension: 'original_extension',
  mime_type: 'mime_type',
  file_size: 'file_size',
  url: 'url',
  path: 'path',
  cuts: 'cuts',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Award_queueScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  users_id: 'users_id',
  description: 'description',
  claimed: 'claimed',
  type_id: 'type_id',
  type: 'type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.BetsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  name: 'name',
  ticket_price: 'ticket_price',
  description: 'description',
  deadline: 'deadline',
  options: 'options',
  icon: 'icon',
  distributed: 'distributed',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Campaign_kpisScalarFieldEnum = {
  id: 'id',
  campaign_id: 'campaign_id',
  kpi_id: 'kpi_id',
  goal_daily: 'goal_daily',
  goal_weekly: 'goal_weekly',
  goal_monthly: 'goal_monthly',
  goal_quarterly: 'goal_quarterly',
  goal_semi_annual: 'goal_semi_annual',
  goal_annual: 'goal_annual',
  weight: 'weight',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Campaign_usersScalarFieldEnum = {
  id: 'id',
  campaign_id: 'campaign_id',
  user_id: 'user_id',
  user_group_id: 'user_group_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.CampaignsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  name: 'name',
  type: 'type',
  manage_by: 'manage_by',
  coaching_goals: 'coaching_goals',
  recognition_goals: 'recognition_goals',
  default_goal: 'default_goal',
  minimum_weight: 'minimum_weight',
  start_date: 'start_date',
  end_date: 'end_date',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.CertificationsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  requirement: 'requirement',
  avatar: 'avatar',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  account_id: 'account_id'
};

exports.Prisma.ChallengesScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  criteria: 'criteria',
  users_id: 'users_id',
  creator_id: 'creator_id',
  work_related: 'work_related',
  name: 'name',
  description: 'description',
  icon: 'icon',
  price: 'price',
  accept_by: 'accept_by',
  end_date: 'end_date',
  done: 'done',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.CoursesScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  session_ids: 'session_ids',
  user_ids: 'user_ids',
  name: 'name',
  description: 'description',
  percentage_approval: 'percentage_approval',
  tags: 'tags',
  enable_timer: 'enable_timer',
  cover_images: 'cover_images',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.DataScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  campaign_id: 'campaign_id',
  entry_date: 'entry_date',
  field_1: 'field_1',
  field_2: 'field_2',
  field_3: 'field_3',
  field_4: 'field_4',
  field_5: 'field_5',
  field_6: 'field_6',
  field_7: 'field_7',
  field_8: 'field_8',
  field_9: 'field_9',
  field_10: 'field_10',
  field_11: 'field_11',
  field_12: 'field_12',
  field_13: 'field_13',
  field_14: 'field_14',
  field_15: 'field_15',
  field_16: 'field_16',
  field_17: 'field_17',
  field_18: 'field_18',
  field_19: 'field_19',
  field_20: 'field_20',
  field_21: 'field_21',
  field_22: 'field_22',
  field_23: 'field_23',
  field_24: 'field_24',
  field_25: 'field_25',
  field_26: 'field_26',
  field_27: 'field_27',
  field_28: 'field_28',
  field_29: 'field_29',
  field_30: 'field_30',
  field_31: 'field_31',
  field_32: 'field_32',
  field_33: 'field_33',
  field_34: 'field_34',
  field_35: 'field_35',
  field_36: 'field_36',
  field_37: 'field_37',
  field_38: 'field_38',
  field_39: 'field_39',
  field_40: 'field_40',
  field_41: 'field_41',
  field_42: 'field_42',
  field_43: 'field_43',
  field_44: 'field_44',
  field_45: 'field_45',
  field_46: 'field_46',
  field_47: 'field_47',
  field_48: 'field_48',
  field_49: 'field_49',
  field_50: 'field_50',
  field_51: 'field_51',
  field_52: 'field_52',
  field_53: 'field_53',
  field_54: 'field_54',
  field_55: 'field_55',
  field_56: 'field_56',
  field_57: 'field_57',
  field_58: 'field_58',
  field_59: 'field_59',
  field_60: 'field_60',
  field_61: 'field_61',
  field_62: 'field_62',
  field_63: 'field_63',
  field_64: 'field_64',
  field_65: 'field_65',
  field_66: 'field_66',
  field_67: 'field_67',
  field_68: 'field_68',
  field_69: 'field_69',
  field_70: 'field_70',
  field_71: 'field_71',
  field_72: 'field_72',
  field_73: 'field_73',
  field_74: 'field_74',
  field_75: 'field_75',
  field_76: 'field_76',
  field_77: 'field_77',
  field_78: 'field_78',
  field_79: 'field_79',
  field_80: 'field_80',
  field_81: 'field_81',
  field_82: 'field_82',
  field_83: 'field_83',
  field_84: 'field_84',
  field_85: 'field_85',
  field_86: 'field_86',
  field_87: 'field_87',
  field_88: 'field_88',
  field_89: 'field_89',
  field_90: 'field_90',
  field_91: 'field_91',
  field_92: 'field_92',
  field_93: 'field_93',
  field_94: 'field_94',
  field_95: 'field_95',
  field_96: 'field_96',
  field_97: 'field_97',
  field_98: 'field_98',
  field_99: 'field_99',
  field_100: 'field_100',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Data_fieldsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  name: 'name',
  code: 'code',
  description: 'description',
  measure_unit: 'measure_unit',
  kpi_order: 'kpi_order',
  kpi_calculation: 'kpi_calculation',
  advanced_config: 'advanced_config',
  formula: 'formula',
  field_map_to: 'field_map_to',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Data_rewardScalarFieldEnum = {
  id: 'id',
  reward_type: 'reward_type',
  account_id: 'account_id',
  user_id: 'user_id',
  campaign_id: 'campaign_id',
  entry_date: 'entry_date',
  field_1: 'field_1',
  field_2: 'field_2',
  field_3: 'field_3',
  field_4: 'field_4',
  field_5: 'field_5',
  field_6: 'field_6',
  field_7: 'field_7',
  field_8: 'field_8',
  field_9: 'field_9',
  field_10: 'field_10',
  field_11: 'field_11',
  field_12: 'field_12',
  field_13: 'field_13',
  field_14: 'field_14',
  field_15: 'field_15',
  field_16: 'field_16',
  field_17: 'field_17',
  field_18: 'field_18',
  field_19: 'field_19',
  field_20: 'field_20',
  field_21: 'field_21',
  field_22: 'field_22',
  field_23: 'field_23',
  field_24: 'field_24',
  field_25: 'field_25',
  field_26: 'field_26',
  field_27: 'field_27',
  field_28: 'field_28',
  field_29: 'field_29',
  field_30: 'field_30',
  field_31: 'field_31',
  field_32: 'field_32',
  field_33: 'field_33',
  field_34: 'field_34',
  field_35: 'field_35',
  field_36: 'field_36',
  field_37: 'field_37',
  field_38: 'field_38',
  field_39: 'field_39',
  field_40: 'field_40',
  field_41: 'field_41',
  field_42: 'field_42',
  field_43: 'field_43',
  field_44: 'field_44',
  field_45: 'field_45',
  field_46: 'field_46',
  field_47: 'field_47',
  field_48: 'field_48',
  field_49: 'field_49',
  field_50: 'field_50',
  field_51: 'field_51',
  field_52: 'field_52',
  field_53: 'field_53',
  field_54: 'field_54',
  field_55: 'field_55',
  field_56: 'field_56',
  field_57: 'field_57',
  field_58: 'field_58',
  field_59: 'field_59',
  field_60: 'field_60',
  field_61: 'field_61',
  field_62: 'field_62',
  field_63: 'field_63',
  field_64: 'field_64',
  field_65: 'field_65',
  field_66: 'field_66',
  field_67: 'field_67',
  field_68: 'field_68',
  field_69: 'field_69',
  field_70: 'field_70',
  field_71: 'field_71',
  field_72: 'field_72',
  field_73: 'field_73',
  field_74: 'field_74',
  field_75: 'field_75',
  field_76: 'field_76',
  field_77: 'field_77',
  field_78: 'field_78',
  field_79: 'field_79',
  field_80: 'field_80',
  field_81: 'field_81',
  field_82: 'field_82',
  field_83: 'field_83',
  field_84: 'field_84',
  field_85: 'field_85',
  field_86: 'field_86',
  field_87: 'field_87',
  field_88: 'field_88',
  field_89: 'field_89',
  field_90: 'field_90',
  field_91: 'field_91',
  field_92: 'field_92',
  field_93: 'field_93',
  field_94: 'field_94',
  field_95: 'field_95',
  field_96: 'field_96',
  field_97: 'field_97',
  field_98: 'field_98',
  field_99: 'field_99',
  field_100: 'field_100',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.ExperienceScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  experience: 'experience',
  level: 'level',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Group_usersScalarFieldEnum = {
  id: 'id',
  group_id: 'group_id',
  user_id: 'user_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.GroupsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  name: 'name',
  description: 'description',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Karma_levelsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  level: 'level',
  point: 'point',
  color: 'color',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Karma_point_logsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  karma_type_id: 'karma_type_id',
  point: 'point',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Karma_pointsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  karma_type_id: 'karma_type_id',
  point: 'point',
  accumulable: 'accumulable',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Karma_typesScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  action: 'action',
  name: 'name',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Kpi_goal_rewardScalarFieldEnum = {
  id: 'id',
  kpi_id: 'kpi_id',
  campaign_id: 'campaign_id',
  goal: 'goal',
  reward: 'reward',
  account_id: 'account_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Lesson_filesScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  lesson_id: 'lesson_id',
  name: 'name',
  file_data: 'file_data',
  file_type: 'file_type',
  file_size: 'file_size',
  account_id: 'account_id',
  created_at: 'created_at'
};

exports.Prisma.LessonsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  session_id: 'session_id',
  title: 'title',
  content: 'content',
  passed: 'passed',
  reward_value: 'reward_value',
  enable_timer: 'enable_timer',
  actual_time: 'actual_time',
  time: 'time',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Lessons_oldScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  session_id: 'session_id',
  quiz_id: 'quiz_id',
  title: 'title',
  content: 'content',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.LevelsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  name: 'name',
  level: 'level',
  icon: 'icon',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.MissionsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  name: 'name',
  requirements: 'requirements',
  description: 'description',
  icon: 'icon',
  reward_amount: 'reward_amount',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Polaris_apiScalarFieldEnum = {
  id: 'id',
  name: 'name',
  section: 'section',
  action: 'action',
  method: 'method',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Polaris_api_payloadScalarFieldEnum = {
  id: 'id',
  parameters: 'parameters',
  response: 'response',
  example_response: 'example_response',
  editable: 'editable',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Session_logsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  session_id: 'session_id',
  current_seconds: 'current_seconds',
  finished: 'finished',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Store_itemsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  status: 'status',
  type: 'type',
  name: 'name',
  icon: 'icon',
  quantity: 'quantity',
  description: 'description',
  level_requirement: 'level_requirement',
  cost: 'cost',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Study_sessionScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  name: 'name',
  account_id: 'account_id',
  course_id: 'course_id',
  lesson_ids: 'lesson_ids',
  deadline: 'deadline',
  duration: 'duration',
  access_after_duration: 'access_after_duration',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.SurveysScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  name: 'name',
  questions: 'questions',
  deadline: 'deadline',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Test_resultsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  test_id: 'test_id',
  user_id: 'user_id',
  result: 'result',
  passed: 'passed',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.TestsScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  name: 'name',
  status: 'status',
  reward_value: 'reward_value',
  number_of_questions: 'number_of_questions',
  allow_back: 'allow_back',
  test_duration: 'test_duration',
  random_order: 'random_order',
  time_before_retake: 'time_before_retake',
  questions: 'questions',
  success_percent: 'success_percent',
  result_type: 'result_type',
  number_of_time: 'number_of_time',
  lesson_id: 'lesson_id',
  deadline: 'deadline',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.TransactionsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  description: 'description',
  amount: 'amount',
  balance: 'balance',
  type: 'type',
  type_id: 'type_id',
  campaign_id: 'campaign_id',
  goal_time: 'goal_time',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.Upload_filesScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  campaign_id: 'campaign_id',
  name: 'name',
  options: 'options',
  file_data: 'file_data',
  file_type: 'file_type',
  file_size: 'file_size',
  row_count: 'row_count',
  row_processed: 'row_processed',
  process_started_at: 'process_started_at',
  status: 'status',
  account_id: 'account_id',
  created_at: 'created_at',
  upload_results: 'upload_results'
};

exports.Prisma.User_accepted_challengeScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  challenge_id: 'challenge_id',
  won: 'won',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.User_achieved_kpisScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  campaign_id: 'campaign_id',
  kpi_id: 'kpi_id',
  goal_time: 'goal_time',
  score: 'score',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.User_achieved_missionsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  mission_id: 'mission_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.User_bet_ticketScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  bet_id: 'bet_id',
  tickets_bought: 'tickets_bought',
  option: 'option',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.User_certificationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  certification_id: 'certification_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  account_id: 'account_id'
};

exports.Prisma.User_completed_tasksScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  type: 'type',
  type_id: 'type_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.User_task_rewardsScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  user_id: 'user_id',
  type: 'type',
  type_id: 'type_id',
  reward_amount: 'reward_amount',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  u_id: 'u_id',
  account_id: 'account_id',
  acl_access_profile: 'acl_access_profile',
  external_user_id: 'external_user_id',
  email: 'email',
  first_name: 'first_name',
  last_name: 'last_name',
  title: 'title',
  level: 'level',
  experience: 'experience',
  ip_address: 'ip_address',
  avatar: 'avatar',
  frame: 'frame',
  last_login_at: 'last_login_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at',
  google_id: 'google_id'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.accountsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  company_name: 'company_name',
  address: 'address',
  address_2: 'address_2',
  city: 'city',
  state: 'state',
  zipcode: 'zipcode',
  country: 'country',
  phone: 'phone',
  website: 'website',
  local_gmt: 'local_gmt',
  cluster_node: 'cluster_node',
  impersonate_key: 'impersonate_key'
};

exports.Prisma.acl_access_profileOrderByRelevanceFieldEnum = {
  section_name: 'section_name'
};

exports.Prisma.acl_access_profile_mainOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.assetsOrderByRelevanceFieldEnum = {
  original_filename: 'original_filename',
  original_extension: 'original_extension',
  mime_type: 'mime_type',
  url: 'url',
  path: 'path',
  cuts: 'cuts'
};

exports.Prisma.award_queueOrderByRelevanceFieldEnum = {
  description: 'description'
};

exports.Prisma.betsOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description',
  options: 'options',
  icon: 'icon'
};

exports.Prisma.campaignsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  type: 'type'
};

exports.Prisma.certificationsOrderByRelevanceFieldEnum = {
  name: 'name',
  requirement: 'requirement',
  avatar: 'avatar',
  description: 'description'
};

exports.Prisma.challengesOrderByRelevanceFieldEnum = {
  criteria: 'criteria',
  users_id: 'users_id',
  name: 'name',
  description: 'description',
  icon: 'icon'
};

exports.Prisma.coursesOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  session_ids: 'session_ids',
  user_ids: 'user_ids',
  name: 'name',
  description: 'description',
  tags: 'tags',
  cover_images: 'cover_images'
};

exports.Prisma.data_fieldsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  code: 'code',
  description: 'description',
  formula: 'formula',
  field_map_to: 'field_map_to'
};

exports.Prisma.groupsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  description: 'description'
};

exports.Prisma.karma_levelsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  level: 'level',
  color: 'color'
};

exports.Prisma.karma_pointsOrderByRelevanceFieldEnum = {
  u_id: 'u_id'
};

exports.Prisma.karma_typesOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  action: 'action',
  name: 'name',
  description: 'description'
};

exports.Prisma.lesson_filesOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  file_type: 'file_type'
};

exports.Prisma.lessonsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  title: 'title',
  content: 'content'
};

exports.Prisma.lessons_oldOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  title: 'title',
  content: 'content'
};

exports.Prisma.levelsOrderByRelevanceFieldEnum = {
  name: 'name',
  icon: 'icon'
};

exports.Prisma.missionsOrderByRelevanceFieldEnum = {
  name: 'name',
  requirements: 'requirements',
  description: 'description',
  icon: 'icon'
};

exports.Prisma.polaris_apiOrderByRelevanceFieldEnum = {
  name: 'name',
  section: 'section',
  action: 'action',
  description: 'description'
};

exports.Prisma.polaris_api_payloadOrderByRelevanceFieldEnum = {
  parameters: 'parameters',
  response: 'response',
  example_response: 'example_response',
  editable: 'editable'
};

exports.Prisma.store_itemsOrderByRelevanceFieldEnum = {
  name: 'name',
  icon: 'icon',
  description: 'description'
};

exports.Prisma.study_sessionOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  lesson_ids: 'lesson_ids'
};

exports.Prisma.surveysOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  questions: 'questions'
};

exports.Prisma.test_resultsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  result: 'result'
};

exports.Prisma.testsOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  questions: 'questions'
};

exports.Prisma.transactionsOrderByRelevanceFieldEnum = {
  description: 'description',
  goal_time: 'goal_time'
};

exports.Prisma.upload_filesOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  name: 'name',
  options: 'options',
  file_type: 'file_type'
};

exports.Prisma.user_achieved_kpisOrderByRelevanceFieldEnum = {
  goal_time: 'goal_time'
};

exports.Prisma.user_bet_ticketOrderByRelevanceFieldEnum = {
  option: 'option'
};

exports.Prisma.usersOrderByRelevanceFieldEnum = {
  u_id: 'u_id',
  email: 'email',
  first_name: 'first_name',
  last_name: 'last_name',
  title: 'title',
  ip_address: 'ip_address',
  avatar: 'avatar',
  frame: 'frame',
  google_id: 'google_id'
};
exports.accounts_status = exports.$Enums.accounts_status = {
  NEW: 'NEW',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DEMO: 'DEMO',
  DELINQUENT: 'DELINQUENT',
  ACTIVE_OVERRIDE: 'ACTIVE_OVERRIDE'
};

exports.acl_access_profile_allow_read = exports.$Enums.acl_access_profile_allow_read = {
  NO: 'NO',
  YES: 'YES'
};

exports.acl_access_profile_allow_write = exports.$Enums.acl_access_profile_allow_write = {
  NO: 'NO',
  YES: 'YES'
};

exports.acl_access_profile_allow_delete = exports.$Enums.acl_access_profile_allow_delete = {
  NO: 'NO',
  YES: 'YES'
};

exports.assets_type = exports.$Enums.assets_type = {
  AVATAR: 'AVATAR',
  ICON: 'ICON'
};

exports.award_queue_claimed = exports.$Enums.award_queue_claimed = {
  YES: 'YES',
  NO: 'NO'
};

exports.award_queue_type = exports.$Enums.award_queue_type = {
  MISSION: 'MISSION',
  CHALLENGE: 'CHALLENGE',
  LEVEL: 'LEVEL'
};

exports.bets_distributed = exports.$Enums.bets_distributed = {
  YES: 'YES',
  NO: 'NO'
};

exports.campaign_kpis_status = exports.$Enums.campaign_kpis_status = {
  Y: 'Y',
  N: 'N'
};

exports.campaigns_default_goal = exports.$Enums.campaigns_default_goal = {
  goal_daily: 'goal_daily',
  goal_weekly: 'goal_weekly',
  goal_monthly: 'goal_monthly',
  goal_quarterly: 'goal_quarterly',
  goal_semi_annual: 'goal_semi_annual',
  goal_annual: 'goal_annual'
};

exports.challenges_work_related = exports.$Enums.challenges_work_related = {
  YES: 'YES',
  NO: 'NO'
};

exports.challenges_done = exports.$Enums.challenges_done = {
  YES: 'YES',
  NO: 'NO'
};

exports.courses_enable_timer = exports.$Enums.courses_enable_timer = {
  Y: 'Y',
  N: 'N'
};

exports.data_fields_measure_unit = exports.$Enums.data_fields_measure_unit = {
  QUANTITY: 'QUANTITY',
  PERCENT: 'PERCENT',
  CURRENCY: 'CURRENCY',
  TIME_MIN: 'TIME_MIN',
  TIME_SEC: 'TIME_SEC'
};

exports.data_fields_kpi_order = exports.$Enums.data_fields_kpi_order = {
  UP: 'UP',
  DOWN: 'DOWN'
};

exports.data_fields_kpi_calculation = exports.$Enums.data_fields_kpi_calculation = {
  SUM: 'SUM',
  AVG: 'AVG',
  MIN: 'MIN',
  MAX: 'MAX'
};

exports.data_reward_reward_type = exports.$Enums.data_reward_reward_type = {
  goal_daily: 'goal_daily',
  goal_weekly: 'goal_weekly',
  goal_monthly: 'goal_monthly',
  goal_quarterly: 'goal_quarterly',
  goal_semi_annual: 'goal_semi_annual',
  goal_annual: 'goal_annual'
};

exports.karma_points_accumulable = exports.$Enums.karma_points_accumulable = {
  N: 'N',
  Y: 'Y'
};

exports.kpi_goal_reward_goal = exports.$Enums.kpi_goal_reward_goal = {
  goal_daily: 'goal_daily',
  goal_weekly: 'goal_weekly',
  goal_monthly: 'goal_monthly',
  goal_quarterly: 'goal_quarterly',
  goal_semi_annual: 'goal_semi_annual',
  goal_annual: 'goal_annual'
};

exports.lessons_passed = exports.$Enums.lessons_passed = {
  Y: 'Y',
  N: 'N'
};

exports.lessons_enable_timer = exports.$Enums.lessons_enable_timer = {
  Y: 'Y',
  N: 'N'
};

exports.polaris_api_method = exports.$Enums.polaris_api_method = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE'
};

exports.session_logs_finished = exports.$Enums.session_logs_finished = {
  Y: 'Y',
  N: 'N'
};

exports.store_items_status = exports.$Enums.store_items_status = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

exports.store_items_type = exports.$Enums.store_items_type = {
  FRAME: 'FRAME',
  PHYSICAL: 'PHYSICAL',
  DIGITAL: 'DIGITAL'
};

exports.study_session_access_after_duration = exports.$Enums.study_session_access_after_duration = {
  N: 'N',
  Y: 'Y'
};

exports.test_results_passed = exports.$Enums.test_results_passed = {
  N: 'N',
  Y: 'Y'
};

exports.tests_status = exports.$Enums.tests_status = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

exports.tests_allow_back = exports.$Enums.tests_allow_back = {
  Y: 'Y',
  N: 'N'
};

exports.tests_random_order = exports.$Enums.tests_random_order = {
  N: 'N',
  Y: 'Y'
};

exports.tests_result_type = exports.$Enums.tests_result_type = {
  score_only: 'score_only',
  each_step: 'each_step',
  end_only: 'end_only'
};

exports.transactions_type = exports.$Enums.transactions_type = {
  KPI: 'KPI',
  LESSON: 'LESSON',
  TEST: 'TEST',
  DIGITAL: 'DIGITAL',
  MISSION: 'MISSION',
  GIFT: 'GIFT',
  FRAME: 'FRAME',
  PHYSICAL: 'PHYSICAL',
  ADJUSTMENT: 'ADJUSTMENT',
  BET: 'BET',
  CHALLENGE: 'CHALLENGE'
};

exports.user_accepted_challenge_won = exports.$Enums.user_accepted_challenge_won = {
  YES: 'YES',
  NO: 'NO'
};

exports.user_completed_tasks_type = exports.$Enums.user_completed_tasks_type = {
  LESSON: 'LESSON',
  TEST: 'TEST',
  SESSION: 'SESSION',
  COURSE: 'COURSE'
};

exports.user_task_rewards_type = exports.$Enums.user_task_rewards_type = {
  LESSON: 'LESSON',
  TEST: 'TEST',
  SESSION: 'SESSION',
  COURSE: 'COURSE'
};

exports.Prisma.ModelName = {
  accounts: 'accounts',
  acl_access_profile: 'acl_access_profile',
  acl_access_profile_main: 'acl_access_profile_main',
  assets: 'assets',
  award_queue: 'award_queue',
  bets: 'bets',
  campaign_kpis: 'campaign_kpis',
  campaign_users: 'campaign_users',
  campaigns: 'campaigns',
  certifications: 'certifications',
  challenges: 'challenges',
  courses: 'courses',
  data: 'data',
  data_fields: 'data_fields',
  data_reward: 'data_reward',
  experience: 'experience',
  group_users: 'group_users',
  groups: 'groups',
  karma_levels: 'karma_levels',
  karma_point_logs: 'karma_point_logs',
  karma_points: 'karma_points',
  karma_types: 'karma_types',
  kpi_goal_reward: 'kpi_goal_reward',
  lesson_files: 'lesson_files',
  lessons: 'lessons',
  lessons_old: 'lessons_old',
  levels: 'levels',
  missions: 'missions',
  polaris_api: 'polaris_api',
  polaris_api_payload: 'polaris_api_payload',
  session_logs: 'session_logs',
  store_items: 'store_items',
  study_session: 'study_session',
  surveys: 'surveys',
  test_results: 'test_results',
  tests: 'tests',
  transactions: 'transactions',
  upload_files: 'upload_files',
  user_accepted_challenge: 'user_accepted_challenge',
  user_achieved_kpis: 'user_achieved_kpis',
  user_achieved_missions: 'user_achieved_missions',
  user_bet_ticket: 'user_bet_ticket',
  user_certifications: 'user_certifications',
  user_completed_tasks: 'user_completed_tasks',
  user_task_rewards: 'user_task_rewards',
  users: 'users'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
